name: Publish

on:
  push:
    branches: [master]

jobs:
  build:
    name: Setup Cocoapods based on provided version
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: Podfile.lock
      
      - name: verify-spec
        run: |
          pod --version
          pod lib lint --use-libraries --allow-warnings
